### ISSUE TITLE
pip req for dateutil should force <2.0.0

### ISSUE THREAD

**Issue by JoshData** [ckan/ckanext-datastorer#14]
According to http://labix.org/python-dateutil, dateutil 2+ is for Python 3 only. If the 2.0 version gets installed, a version conflict arises because celery requires < 2.0.

pip-requirements.txt should be revised to have:  python-dateutil<2.0.0

**Comment by domoritz** [comment]
Should be fixed soon. However, there are other major issues with messytables that we are working on. See issue #16.

**Comment by JoshData** [comment]
Yeah I've been digging into messytables a bit too --- will have some pull requests over there too soonish.

**Comment by domoritz** [comment]
@tauberer That's awesome. @pudo wanted to fix some issues and I might have fixed some stuff on my fork as well. The requirements issue is definitely fixed in fa9bb1a

**Comment by JoshData** [comment]
I think we can close this? It also ended up dup'd in my pull request (#17).

**Comment by domoritz** [comment]
@tauberer I'll close the issue as soon as we merge one of the pull requests that explicitly set the version. Thanks for the patches.
