### ISSUE TITLE
Errors when importing CSV files

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-datastorer#20]
When importing this file, there are some errors on the celey log and not all rows are imported (original file has ~5155 rows):

http://www.newcastle.gov.uk/sites/drupalncc.newcastle.gov.uk/files/wwwfileroot/your-council/local_transparency/april_2012.csv

See traceback here:
https://gist.github.com/3986570

Resource on thedatahub.org:
http://thedatahub.org/dataset/newcastle-city-council-payments-over-500/resource/b12b7665-8981-40a5-96e1-8b0a4874976f

**Comment by domoritz** [comment]
I noticed that the csv is a little bit broken:

``` csv
,,,,,,,,,
,,,,,,,,,
,,,,,,,,,
,,,,,,,,,
,,,,,,,,,
,,,,,,,,,
,,,,,,,,,
,,,,,,,,,
,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
```

I don't want to change the datastorer to adapt to every possible error. Is this something that occurs regularly and is urgent? If not, I would like to address this issue with the new datastorer service instead of this extension. Is that okay?

**Comment by amercader** [comment]
Absolutely, issues are not calls to immediate action, they of course need to be assessed. If this is not a wider issue it can be archived.
