### ISSUE TITLE
Support for Separator and Encoding Guessing or Configuration for CSVs

### ISSUE THREAD

**Issue by rufuspollock** [ckan/ckanext-datastorer#4]
e.g. many csvs use ';' rather than ','

**Comment by kindly** [comment]
Messy tables should detect ; and tabs.  If this is not working please give example file.

**Comment by rufuspollock** [comment]
http://datahub.io/dataset/land-matrix/resource/f46a9192-cf2b-410e-b4f7-dc80538e5541 - again seems that import has failed entirely here (please remind me how I can find out about this sort of info :-)

**Comment by kindly** [comment]
Works for me. Celeryd crashed badly when running the qa tasks and stopped everything.

We also now have got an api call to see what is happening in 1.7.

curl http://datahub.io/api/action/resource_status_show -d '{"id": "f46a9192-cf2b-410e-b4f7-dc80538e5541"}'
