### ISSUE TITLE
Error with read-only resources

### ISSUE THREAD

**Issue by anibalpacheco** [ckan/ckanext-datastorer#59]
Every task related to datastore raises an error regarding to read-only resources, where is that read-only set?

example:
$ paster datastore_upload test5 -c ../ckan/development.ini 
2013-10-30 16:41:43,036 DEBUG [ckanext.archiver.plugin] Notified of resource event: 2eaa3568-8442-4228-923e-1af417dd869e
2013-10-30 16:41:43,036 DEBUG [ckanext.archiver.plugin] Ignoring resource event because operation is: changed
2013-10-30 16:41:44,260 WARNI [root] Resource downloaded: id=2eaa3568-8442-4228-923e-1af417dd869e url=u'http://localhost:5000/storage/f/2013-10-30T18%3A40%3A50.898Z/201212-1.csv' cache_filename=/tmp/tmp_wm11j length=4112 hash=bd185413696e07808f20e8d0a03c5fadd4d42977
2013-10-30 16:41:44,312 ERROR [root] {'read-only': ['Cannot edit read-only resource. Either pass"force=True" or change url-type to "datastore"']}

**Comment by ilkosta** [comment]
+1

**Comment by amercader** [comment]
@anibalpacheco @ilkosta What version of CKAN and the datastorer are you using?
I can't seem to find this message anywhere.
@kindly does this ring a bell? Is it because of the datastorer not working on recent CKAN versions?

**Comment by anibalpacheco** [comment]
@amercader master branch on both

**Comment by ilkosta** [comment]
@amercader master branch on both, just pulled from git and recreated databases

**Comment by amercader** [comment]
I don't think that this extension works any more with current CKAN master. Its functionality is being moved to the datapusher, see here for details:

https://github.com/okfn/ckan/wiki/Viewing-Resource-Data#current-plans

**Comment by kindly** [comment]
This should be a simple fix to the extension, by adding force=True here.
https://github.com/okfn/ckanext-datastorer/blob/master/ckanext/datastorer/tasks.py#L136

i.e
request = {'resource_id': resource['id'],
                'fields': [dict(id=name, type=typename) for name, typename in zip(headers, guessed_type_names)],
                'records': data, 'force':True}

could someone with a working setup test this for me?

**Comment by anibalpacheco** [comment]
@kindly Didn't work for me, same errors.

**Comment by anibalpacheco** [comment]
@amercader Tried the datapusher but it's not clear how it works, I could post a job perfectly, ¿but then?

**Comment by kindly** [comment]
@anibalpacheco @ilkosta 

This has been fixed in ckanext-datastorer master now cd68d60b92a4947d6e7c6b9ea18dcf.  Nonetheless, we are trying to convert people over to the datapusher for the next release.  New docs for this are here.

http://datapusher.readthedocs.org/en/latest/
