### ISSUE TITLE
Datastorer does not handle byte-order marker in UTF8 CSV files

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckanext-datastorer#63]
When processing CSV files, the datastorer apparently does not look for the byte-order marker indicating a UTF-8 file. This results in a database table schema such as:

<pre>
_id                 | integer  | not null default nextval('"<uuid>__id_seq"'::regclass)
_full_text          | tsvector | 
&lt;U+FEFF&gt; Category   | text     | 
Category name       | text     |
...
</pre>

which does not respond properly to queries, due to the extra character.

We would like to use UTF-8 so that we can process data containing em-dashes. Is there a way to do this?

**Comment by rossjones** [comment]
That BOM looks like UTF-16 rather than UTF-8. Is it left over from a conversion of some sort? 

Obviously still a problem that it doesnt strip non printable bytes/chars though.

**Comment by ThrawnCA** [comment]
This is obsolete.
